use_frameworks!

platform :ios, '8.0'

target 'ZJBTableViewModel_Example' do
  pod 'ZJBTableViewModel', :path => '../'

  target 'ZJBTableViewModel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
